Update python release process

diff --git a/.github/workflows/pypi-publish-on-release.yml b/.github/workflows/pypi-publish-on-release.yml
--- a/.github/workflows/pypi-publish-on-release.yml
+++ b/.github/workflows/pypi-publish-on-release.yml
@@ -4,7 +4,6 @@ on:
   release:
     types:
       - published
-  workflow_dispatch:
 
 jobs:
   build:
@@ -26,12 +25,24 @@ jobs:
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
-        pip install build
+        pip install hatch
+
+    - name: Validate version
+      run: |
+        cd python
+        version=$(hatch version)
+        if [[ $version =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "Valid version format"
+            exit 0
+        else
+            echo "Invalid version format"
+            exit 1
+        fi
 
     - name: Build
       run: |
         cd python
-        python -m build
+        hatch build
 
     - name: Store the distribution packages
       uses: actions/upload-artifact@v5
@@ -40,22 +51,27 @@ jobs:
         path: python/dist/
 
   deploy:
-    name: Upload release to PyPI
+    name: Upload release to PyPI Test
     needs:
     - build
     runs-on: ubuntu-latest
 
+    # environment is used by PyPI Trusted Publisher and is strongly encouraged
+    # https://docs.pypi.org/trusted-publishers/adding-a-publisher/
     environment:
-      name: pypi
-      url: https://pypi.org/p/strands-agents
+      name: testpypi
+      url: https://test.pypi.org/p/strands-agents
     permissions:
+      # IMPORTANT: this permission is mandatory for Trusted Publishing
       id-token: write
     
     steps:
     - name: Download all the dists
-      uses: actions/download-artifact@v6
+      uses: actions/download-artifact@v5
       with:
         name: python-package-distributions
         path: dist/
-    - name: Publish distribution 📦 to PyPI
+    - name: Publish distribution 📦 to PyPI Test
       uses: pypa/gh-action-pypi-publish@release/v1
+      with:
+        repository-url: https://test.pypi.org/legacy/
